In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.cluster
from sklearn.cluster import KMeans
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
import numpy as np
import plotly.graph_objs as go

In [2]:
data = pd.read_csv(r'C:\Users\benja\Downloads\dg_course_table.csv')

In [3]:
data.head(90)

,course,par,yardage,yardage_4_5,yardage_3,adj_score_to_par,adj_par_3_score,adj_par_4_score,adj_par_5_score,adj_driving_distance,...,miss_fw_pen_frac,adj_gir,less_150_sg,greater_150_sg,arg_fairway_sg,arg_rough_sg,arg_bunker_sg,less_5_ft_sg,greater_5_less_15_sg,greater_15_sg
0,Albany GC,72,7309,490,187,-1.06,0.02,0.04,-0.30,302.4,...,0.0843,0.5840,-0.002,0.000,-0.084,-0.021,-0.094,-0.013,0.084,0.023
1,Arnold Palmer's Bay Hill Club &amp; Lodge,72,7351,465,209,1.06,0.16,0.15,-0.29,281.3,...,0.0574,0.5745,-0.048,-0.047,0.005,-0.062,0.017,0.001,0.004,-0.006
2,Aronimink GC,70,7036,446,199,-1.14,0.04,-0.03,-0.46,286.3,...,0.0044,0.7424,0.017,0.063,-0.029,-0.027,0.027,0.004,0.026,0.008
3,Augusta National Golf Club,72,7470,481,182,2.12,0.18,0.24,-0.25,293.5,...,0.0254,0.5723,-0.077,-0.049,-0.105,-0.009,-0.028,-0.003,-0.032,-0.053
4,Austin Country Club,71,6899,449,179,-2.09,0.00,-0.07,-0.52,300.8,...,0.0518,0.7087,0.000,0.021,0.013,0.024,0.011,0.002,0.018,-0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Vidanta Vallarta,71,7325,494,181,-1.28,0.02,0.03,-0.41,298.9,...,0.0677,0.6741,0.044,0.010,0.036,0.084,0.028,0.001,0.007,0.010
84,Waialae Country Club,70,7023,449,185,-1.23,0.03,0.00,-0.66,291.0,...,0.0363,0.6952,0.044,0.030,0.033,0.023,0.045,0.000,0.003,0.007
85,Whistling Straits,72,7313,467,192,1.03,0.12,0.16,-0.26,283.7,...,0.0196,0.6018,-0.075,0.002,-0.018,-0.074,-0.241,0.005,0.034,-0.007
86,Wilmington Country Club,71,7424,475,194,0.17,0.10,0.03,-0.19,303.3,...,0.0000,0.6523,-0.015,0.009,-0.009,-0.024,0.050,-0.001,0.030,0.001
87,Winged Foot GC,70,7392,470,204,4.45,0.29,0.29,-0.11,288.6,...,0.0032,0.5063,-0.008,-0.018,-0.049,-0.115,-0.022,-0.015,-0.024,-0.058

In [4]:
alp_course = data['course'].sort_values(ascending=True).tolist()

In [5]:
grass_data = {'course': alp_course, 
              'greens': ['bermudagrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'poa annua', 'bentgrass', 'poa annua', 'bentgrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bermudagrass', 'poa trivialis', 'poa trivialis', 'poa trivialis', 'bentgrass', 'bentgrass', 'bentgrass', 'poa trivialis', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'paspalum', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bentgrass', 'poa annua', 'poa annua', 'poa trivialis', 'poa annua', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'poa annua', 'bentgrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'poa annua', 'bentgrass', 'fescue', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'paspalum', 'bentgrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'poa trivialis', 'poa trivialis', 'poa trivialis', 'bermudagrass', 'bentgrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'bentgrass', 'poa annua', 'bentgrass', 'bentgrass', 'poa annua', 'bermudagrass', 'bentgrass', 'paspalum', 'bermudagrass', 'bentgrass', 'bentgrass', 'poa annua'], 
              'gheight': [.090, .11, .1, .125, .1, .09, .125, .1, .105, 0, .1, 0, .1, .1, .1, .1, 0, .12, .1, .115, 0, .1, .115, .115, .12, 0, .1, .125, .11, .09, .09, 0, 0, .09, .095, .12, .115, 0, .125, .11, .11, .1, .11, .125, .125, .125, 0, .115, .15, .09, .12, 0, .09, 0, .114, .138, .115, .12, .1, .1, .1, 0, .14, .11, .1, .115, .11, .1, .1, .09, .125, .1, .1, .11, 0, .1, .125, .1, .09, .1, .95, .1, 0, 0, 0, .1, .1, .11],
              'fairways': ['bermudagrass', 'bermudagrass', 'bentgrass', 'ryegrass', 'bermudagrass', 'bentgrass', 'zoysia', 'poa annua', 'bentgrass', 'kikuyu', 'bermudagrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bermudagrass', 'zoysia', 'bentgrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'poa trivialis', 'ryegrass', 'ryegrass', 'bentgrass', 'bentgrass', 'bentgrass', 'ryegrass', 'bentgrass', 'bentgrass', 'bentgrass', 'bentgrass', 'paspalum', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'poa annua', 'poa annua', 'ryegrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'poa annua', 'bentgrass', 'fescue', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'fescue', 'bentgrass', 'bentgrass', 'zoysia', 'zoysia', 'bentgrass', 'paspalum', 'poa annua', 'bermudagrass', 'bentgrass', 'bentgrass', 'ryegrass', 'bermudagrass', 'poa trivialis', 'bermudagrass', 'zoysia', 'bermudagrass', 'bentgrass', 'bermudagrass', 'bermudagrass', 'bentgrass', 'bentgrass', 'kikuyu', 'bermudagrass', 'bermudagrass', 'kikuyu', 'zoysia', 'bentgrass', 'paspalum', 'bermudagrass', 'fescue', 'bentgrass', 'poa annua'],
              'fheight': [.4, .35, .35, .375, .375, .325, .5, .4, .4, 0, .35, 0, .3, .35, .4, .375, .35, .55, .3, .4, 0, .45, .375, .375, .45, 0, .375, .35, .4, .35, .375, 0, 0, .3, .4, .45, .4, 0, .4, .425, .35, .35, .375, .35, .45, .437, 0, .35, .395, .4, .4, .35, .35, 0, .55, .354, .3, .375, .425, .45, .39, 0, .5, .5, .325, .375, .4, .275, .4, .425, .5, .3, .35, .45, .375, .4, .4, .35, .45, .425, .425, .375, 0, 0, 0, .4, .39, .3], 
              'rough': ['bermudagrass', 'bermudagrass', 'mix', 'ryegrass', 'bermudagrass', 'kentucky bluegrass', 'tall fescue', 'kentucky bluegrass', 'tall fescue', 'kikuyu', 'bermudagrass', 'sand', 'tall fescue', 'kentucky bluegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'bermudagrass', 'bermudagrass', 'kentucky bluegrass', 'kentucky bluegrass', 'bermudagrass', 'ryegrass', 'poa trivialis', 'ryegrass', 'ryegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'ryegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'kentucky bluegrass', 'bermudagrass', 'kentucky bluegrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'ryegrass', 'ryegrass', 'bermudagrass', 'kentucky bluegrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'kentucky bluegrass', 'kentucky bluegrass', 'tall fescue', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'ryegrass', 'kentucky bluegrass', 'bermudagrass', 'tall fescue', 'kentucky bluegrass', 'kentucky bluegrass', 'bermudagrass', 'bermudagrass', 'kentucky bluegrass', 'paspalum', 'poa annua', 'bermudagrass', 'tall fescue', 'kentucky bluegrass', 'ryegrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'kentucky bluegrass', 'bermudagrass', 'bermudagrass', 'bermudagrass', 'kentucky bluegrass', 'kentucky bluegrass', 'kikuyu', 'bermudagrass', 'kikuyu', 'kikuyu', 'zoysia', 'kentucky bluegrass', 'paspalum', 'bermudagrass', 'tall fescue', 'tall fescue', 'kentucky bluegrass'], 
              'rheight': [1.5, 3, 3, 1.375, 2, 5, 3, 3.5, 3, 0, 3, 0, 3, 3.5, 3.5, 4, 2.5, 2.25, 3.25, 3, 0, 1.25, 3.5, 1.25, 3.75, 0, 3, 2.5, 1.25, 4, 3, 0, 4, 3.5, 4, 2.125, 2.5, 0, 2.5, 4, 2, 3.5, 2.5, 2, 2.25, 2.25, 0, 3.5, 2, 2, 2.5, 2, 3, 0, 2.25, 1.65, 3.5, 4, 2.5, 2.75, 4, 0, 3.5, 1.75, 3, 4, 2.25, 3.5, 3, 2.5, 2.25, 4, 1.25, 2, 3.5, 3, 3, 2, 3, 3, 3, 0, 0, 0, 0, 3.25, 4, 4.25], 
              'soil': ['sandy', 'sandy loam', 'loam', 'clay', 'sandy loam', 'sandy loam', 'none', 'sandy', 'sand capped', 'none', 'clay', 'sandy', 'clay', 'none', 'clay', 'clay loam', 'sandy loam', 'clay', 'loam', 'clay', 'none', 'clay', 'loam', 'sandy loam', 'none', 'sandy loam', 'sand capped', 'loam', 'sand capped', 'clay', 'clay', 'sandy loam', 'none', 'sandy', 'loam', 'loam', 'loam', 'none', 'sandy loam', 'sandy loam', 'none', 'sandy loam', 'clay', 'clay', 'clay', 'loam', 'sandy loam', 'clay', 'sandy', 'clay', 'clay', 'sand capped', 'sandy', 'none', 'clay loam', 'sandy', 'sandy loam', 'loam', 'sand capped', 'sand capped', 'clay', 'none', 'sandy loam', 'sandy', 'clay', 'sandy loam', 'sand capped', 'sandy loam', 'sand capped', 'clay', 'loam', 'sandy', 'sandy loam', 'sand capped', 'none', 'none', 'none', 'loam', 'sand capped', 'clay', 'clay', 'sandy loam', 'none', 'none', 'none', 'none', 'clay loam', 'loam'],
              'bunkers': [52, 84, 176, 44, 110, 138, 76, 78, 0, 0, 84, 250, 99, 0, 89, 87, 74, 74, 82, 93, 0, 60, 88, 54, 74, 76, 98, 71, 21, 68, 74, 78, 57, 150, 91, 60, 60, 0, 116, 118, 90, 0, 93, 61, 60, 53, 81, 65, 84, 47, 52, 74, 51, 0, 88, 110, 104, 64, 83, 83, 76, 0, 47, 101, 80, 69, 64, 92, 67, 75, 92, 72, 73, 56, 0, 85, 82, 58, 62, 42, 82, 88, 0, 0, 83, 200, 91, 76],
              'waterholes': [5, 9, 4, 5, 5, 5, 16, 1, 5, 0, 6, 10, 5, 6, 8, 1, 7, 4, 3, 12, 0, 8, 9, 0, 9, 6, 12, 2, 4, 13, 13, 6, 0, 6, 8, 15, 15, 0, 1, 1, 7, 12, 4, 0.001, 4, 4, 10, 0, 10, 0, 13, 6, 9, 8, 0, 15, 2, 3, 4, 13, 13, 3, 0, 0.001, 5, 10, 5, 3, 18, 6, 11, 4, 15, 12, 0, 9, 4, 0.001, 7, 0.001, 1, 0.001, 0, 0, 5, 1, 4, 2] 
              }
grass_df = pd.DataFrame.from_dict(grass_data)

In [6]:
grass_df['soil'].unique()

array(['sandy', 'sandy loam', 'loam', 'clay', 'none', 'sand capped',
       'clay loam'], dtype=object)

In [7]:
categorical_columns = grass_df[['greens', 'fairways', 'rough', 'soil']].columns.tolist()

In [8]:
ohencoder = OneHotEncoder(sparse_output=False)

In [9]:
one_hot_encoded = ohencoder.fit_transform(grass_df[categorical_columns])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=ohencoder.get_feature_names_out(categorical_columns))

In [10]:
df_concat = pd.concat([data, one_hot_df], axis=1)
df_concat.head(40)

,course,par,yardage,yardage_4_5,yardage_3,adj_score_to_par,adj_par_3_score,adj_par_4_score,adj_par_5_score,adj_driving_distance,...,rough_sand,rough_tall fescue,rough_zoysia,soil_clay,soil_clay loam,soil_loam,soil_none,soil_sand capped,soil_sandy,soil_sandy loam
0,Albany GC,72,7309,490,187,-1.06,0.02,0.04,-0.30,302.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Arnold Palmer's Bay Hill Club &amp; Lodge,72,7351,465,209,1.06,0.16,0.15,-0.29,281.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Aronimink GC,70,7036,446,199,-1.14,0.04,-0.03,-0.46,286.3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Augusta National Golf Club,72,7470,481,182,2.12,0.18,0.24,-0.25,293.5,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Austin Country Club,71,6899,449,179,-2.09,0.00,-0.07,-0.52,300.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,Baltusrol GC,70,7282,461,207,0.88,0.06,0.09,-0.25,280.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,Bellerive CC,70,7248,462,195,0.42,0.08,0.05,-0.27,284.9,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,Bethpage Black,71,7355,469,196,2.11,0.16,0.18,-0.23,287.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8,Caves Valley Golf Club,72,7424,471,209,-1.90,0.04,-0.05,-0.39,290.2,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,Club de Golf Chapultepec,71,7287,464,197,0.43,0.18,0.05,-0.27,299.7,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,Colonial Country Club,70,6995,445,194,0.59,0.09,0.06,-0.23,280.1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Congaree Golf Club,71,7364,473,188,0.08,0.10,0.05,-0.29,301.2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,Congressional CC (Blue),71,7416,474,195,0.03,0.00,0.05,-0.19,288.1,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Conway Farms GC,71,6987,445,191,-0.81,0.11,-0.02,-0.34,281.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,Crooked Stick GC,72,7474,478,195,-0.32,0.13,0.07,-0.38,284.2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Detroit Golf Club,72,7320,470,183,-1.94,0.01,-0.04,-0.38,297.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
16,Eagle Point Golf Club,72,7291,470,176,0.70,0.11,0.07,-0.11,284.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,East Lake Golf Club,70,7280,461,205,0.57,0.13,0.08,-0.46,290.9,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Firestone CC (South),70,7337,467,200,1.48,0.09,0.12,-0.18,298.8,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19,Glen Abbey GC,72,7197,466,168,-1.05,0.06,0.05,-0.44,299.9,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Glen Oaks Club,70,7246,460,201,1.61,0.14,0.13,-0.23,285.9,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
21,Golf Club of Houston,72,7319,468,192,-0.51,0.05,0.04,-0.27,280.5,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Hamilton Golf &amp; Country Club,70,6832,430,202,-0.62,0.09,0.00,-0.47,285.3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,Harbour Town Golf Links,71,6971,446,183,-0.15,0.12,0.04,-0.34,275.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
24,Innisbrook Resort (Copperhead Course),71,7080,469,198,0.67,0.12,0.11,-0.23,277.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
25,Keene Trace Golf Club (Champions Course),72,7143,456,188,-3.14,-0.03,-0.07,-0.58,293.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26,Liberty National Golf Club,71,7201,460,190,-0.30,0.05,0.07,-0.43,286.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
27,Medinah Country Club (No. 3),72,7470,477,199,-1.16,0.05,0.01,-0.36,290.6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
28,Memorial Park Golf Course,70,7099,479,177,0.67,0.08,0.09,-0.22,292.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29,Muirfield Village Golf Club,72,7347,471,188,0.98,0.18,0.13,-0.25,286.4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
30,Muirfield Village Golf Club (Workday),72,7311,470,187,0.07,0.16,0.05,-0.27,292.2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
31,Oak Hill Country Club,70,7339,469,196,2.86,0.16,0.19,-0.03,288.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32,Oakdale Golf &amp; Country Club,72,7231,445,188,-0.76,-0.02,0.03,-0.37,282.4,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
33,Ocean Course at Kiawah Island,72,7671,489,207,2.57,0.29,0.21,-0.17,293.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34,Olympia Fields Country Club (North Course),70,7283,464,196,1.54,0.11,0.12,-0.16,293.6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
35,PGA National Resort (The Champion - Par 71),71,7066,451,185,-0.82,0.16,0.01,-0.53,279.6,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
36,PGA National Resort (The Champion),70,7020,448,187,1.41,0.19,0.11,-0.35,277.1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
37,PGA West (Palmer),72,6844,460,173,-1.98,0.03,0.05,-0.51,277.8,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
38,Pebble Beach Golf Links,72,6888,443,171,-0.61,0.05,0.03,-0.28,272.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,Pebble Beach Golf Links (U.S. Open),71,7003,450,176,1.61,0.11,0.15,-0.16,270.2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
labels = df_concat['course']
numeric_data = df_concat.drop(['course', 'fw_diff', 'rgh_diff', 'non_rgh_diff'], axis=1)

In [19]:
labels

0                                     Albany GC
1     Arnold Palmer's Bay Hill Club &amp; Lodge
2                                  Aronimink GC
3                    Augusta National Golf Club
4                           Austin Country Club
                        ...
83                             Vidanta Vallarta
84                         Waialae Country Club
85                            Whistling Straits
86                      Wilmington Country Club
87                               Winged Foot GC
Name: course, Length: 88, dtype: object

In [12]:
numeric_data.head(100)

,par,yardage,yardage_4_5,yardage_3,adj_score_to_par,adj_par_3_score,adj_par_4_score,adj_par_5_score,adj_driving_distance,adj_sd_distance,...,rough_sand,rough_tall fescue,rough_zoysia,soil_clay,soil_clay loam,soil_loam,soil_none,soil_sand capped,soil_sandy,soil_sandy loam
0,72,7309,490,187,-1.06,0.02,0.04,-0.30,302.4,17.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,72,7351,465,209,1.06,0.16,0.15,-0.29,281.3,18.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,7036,446,199,-1.14,0.04,-0.03,-0.46,286.3,16.5,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,72,7470,481,182,2.12,0.18,0.24,-0.25,293.5,21.4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,71,6899,449,179,-2.09,0.00,-0.07,-0.52,300.8,21.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,71,7325,494,181,-1.28,0.02,0.03,-0.41,298.9,17.4,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
84,70,7023,449,185,-1.23,0.03,0.00,-0.66,291.0,21.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
85,72,7313,467,192,1.03,0.12,0.16,-0.26,283.7,17.5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
86,71,7424,475,194,0.17,0.10,0.03,-0.19,303.3,21.4,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
87,70,7392,470,204,4.45,0.29,0.29,-0.11,288.6,23.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [13]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(numeric_data)

In [14]:
X_scaled

array([[ 1.09270057,  0.5010602 ,  2.04451345, ..., -0.35805744,
         2.96273147, -0.48932261],
       [ 1.09270057,  0.72518201,  0.20034388, ..., -0.35805744,
        -0.33752637,  2.0436415 ],
       [-1.2815624 , -0.95573155, -1.201225  , ..., -0.35805744,
        -0.33752637, -0.48932261],
       ...,
       [ 1.09270057,  0.52240513,  0.34787744, ..., -0.35805744,
        -0.33752637, -0.48932261],
       [-0.09443091,  1.11472705,  0.9380117 , ..., -0.35805744,
        -0.33752637, -0.48932261],
       [-1.2815624 ,  0.94396758,  0.56917779, ..., -0.35805744,
        -0.33752637, -0.48932261]])

In [15]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

In [17]:
from sklearn.neighbors import NearestNeighbors

def labels_ranked_by_proximity(input_label, X, labels, n_neighbors=5):
    # Find the index of the input label
    input_label_index = labels.index(input_label)
    
    # Use NearestNeighbors to find the nearest neighbors of the input label
    nn = NearestNeighbors(n_neighbors=n_neighbors + 1)  # +1 to exclude the input label itself
    nn.fit(X)
    distances, indices = nn.kneighbors([X[input_label_index]])
    
    # Get the labels of the nearest neighbors
    ranked_labels = [(labels[idx], distances[0][i+1]) for i, idx in enumerate(indices[0][1:])]
    
    return ranked_labels

# Example usage

In [21]:
input_label = 'Albany GC'  # Input your label here
labels_list = df_concat['course'].tolist()  # Convert Series to list
ranked_labels = labels_ranked_by_proximity(input_label, X_pca, labels_list, n_neighbors=10)
print(f"Labels ranked by proximity to '{input_label}':")
for label, distance in ranked_labels:
    print(f"Label: {label}, Distance: {distance}")

Labels ranked by proximity to 'Albany GC':
Label: Congaree Golf Club, Distance: 1.878696567567018
Label: The Concession Golf Club, Distance: 2.9962895362259427
Label: Plantation Course at Kapalua, Distance: 3.3559139990066384
Label: Shadow Creek Golf Course, Distance: 3.4257917466821795
Label: TPC Summerlin, Distance: 3.7197681075630933
Label: Whistling Straits, Distance: 4.113857855763619
Label: Trinity Forest Golf Club, Distance: 4.472675928524873
Label: TPC Twin Cities, Distance: 4.609447550979249
Label: TPC Louisiana, Distance: 4.782601230374854
Label: Austin Country Club, Distance: 4.782930388686115

In [22]:
def plot_kmeans_results_with_labels(X, labels, k, random_state=42):
    # Fit KMeans clustering with increased number of iterations and fixed random state
    kmeans = KMeans(n_clusters=k, n_init=1000, random_state=random_state)
    kmeans.fit(X)
    
    # Get cluster labels
    kmeans_labels = kmeans.labels_
    
    # Create a dictionary to store clusters and labels
    clusters = {f'Cluster {i+1}': [] for i in range(k)}
    
    # Add labels to clusters
    for i, label in enumerate(labels):
        clusters[f'Cluster {kmeans_labels[i]+1}'].append(label)
    
    # Plot clusters
    scatter = go.Scatter(
        x=X[:, 0],
        y=X[:, 1],
        mode='markers',
        text=labels,
        hoverinfo='text',
        marker=dict(color=kmeans_labels, size=8, opacity=0.7)
    )

    centroid = go.Scatter(
        x=kmeans.cluster_centers_[:, 0],
        y=kmeans.cluster_centers_[:, 1],
        mode='markers',
        marker=dict(color='black', size=12, symbol='x')
    )
    
    layout = go.Layout(
        plot_bgcolor='white'  # Set background color to white
    )

    fig = go.Figure(data=[scatter, centroid], layout=layout)
    fig.show()
    
    return clusters

In [24]:
clusters = plot_kmeans_results_with_labels(X_pca, labels, k=20)
print(clusters)

{'Cluster 1': ['Detroit Golf Club', 'Golf Club of Houston', 'Liberty National Golf Club', 'Medinah Country Club (No. 3)', 'PGA National Resort (The Champion - Par 71)', 'PGA West (Palmer)', 'Pete Dye Stadium Course', 'Robert Trent Jones GC', 'The Country Club of Jackson', 'The Old White TPC', 'Vidanta Vallarta'], 'Cluster 2': ['Colonial Country Club', 'Memorial Park Golf Course', 'PGA National Resort (The Champion)', 'Pebble Beach Golf Links', 'Ridgewood CC', 'Silverado Resort and Spa (North Course)', "St. George's G&amp;CC", 'TPC Boston', 'TPC Harding Park', 'TPC Potomac at Avenel Farm'], 'Cluster 3': ['Augusta National Golf Club', 'Ocean Course at Kiawah Island'], 'Cluster 4': ['St. Andrews Links (Old Course)'], 'Cluster 5': ['Plantation Course at Kapalua', 'Trinity Forest Golf Club'], 'Cluster 6': ['Aronimink GC', 'Caves Valley Golf Club', 'Keene Trace Golf Club (Champions Course)', 'RTJ Trail (Grand National)', 'Sea Island Golf Club (Seaside)', 'Sedgefield Country Club', 'TPC Deere Run', 'Waialae Country Club'], 'Cluster 7': ['Torrey Pines South (U.S. Open)'], 'Cluster 8': ['Albany GC', 'Congaree Golf Club'], 'Cluster 9': ['Eagle Point Golf Club', 'Muirfield Village Golf Club (Workday)', 'Quail Hollow Club', 'TPC San Antonio (Oaks Course)', 'Wilmington Country Club'], 'Cluster 10': ['Baltusrol GC', 'Congressional CC (Blue)', 'Hamilton Golf &amp; Country Club', 'Harbour Town Golf Links', 'Oakdale Golf &amp; Country Club'], 'Cluster 11': ['Bethpage Black', 'Club de Golf Chapultepec', 'Oak Hill Country Club', 'Pebble Beach Golf Links (U.S. Open)'], 'Cluster 12': ['Bellerive CC', 'Conway Farms GC', 'Crooked Stick GC', 'East Lake Golf Club', 'Glen Abbey GC', 'TPC Four Seasons Resort', 'TPC River Highlands', 'TPC Scottsdale (Stadium Course)', 'TPC Southwind'], 'Cluster 13': ["Arnold Palmer's Bay Hill Club &amp; Lodge", 'Glen Oaks Club', 'Muirfield Village Golf Club', 'TPC Sawgrass (THE PLAYERS Stadium Course)', 'The Los Angeles Country Club (North Course)', 'Trump National Doral'], 'Cluster 14': ['TPC Craig Ranch', 'TPC Craig Ranch (Par 71)', 'The Summit Club'], 'Cluster 15': ['Shadow Creek Golf Course', 'The Concession Golf Club'], 'Cluster 16': ['Firestone CC (South)', 'Innisbrook Resort (Copperhead Course)', 'Olympia Fields Country Club (North Course)', 'Plainfield CC', 'The Renaissance Club', 'The Riviera Country Club', 'Torrey Pines Golf Course (South Course)'], 'Cluster 17': ['Quail Hollow Club (PGA Championship)', 'Southern Hills Country Club'], 'Cluster 18': ['Winged Foot GC'], 'Cluster 19': ['Royal Liverpool', 'Whistling Straits'], 'Cluster 20': ['Austin Country Club', 'Sherwood Country Club', 'TPC Louisiana', 'TPC Summerlin', 'TPC Twin Cities']}

In [25]:
clusters_df = pd.DataFrame.from_dict(clusters, orient='index').transpose()
clusters_df

,Cluster 1,Cluster 2,Cluster 3,Cluster 4,Cluster 5,Cluster 6,Cluster 7,Cluster 8,Cluster 9,Cluster 10,Cluster 11,Cluster 12,Cluster 13,Cluster 14,Cluster 15,Cluster 16,Cluster 17,Cluster 18,Cluster 19,Cluster 20
0,Detroit Golf Club,Colonial Country Club,Augusta National Golf Club,St. Andrews Links (Old Course),Plantation Course at Kapalua,Aronimink GC,Torrey Pines South (U.S. Open),Albany GC,Eagle Point Golf Club,Baltusrol GC,Bethpage Black,Bellerive CC,Arnold Palmer's Bay Hill Club &amp; Lodge,TPC Craig Ranch,Shadow Creek Golf Course,Firestone CC (South),Quail Hollow Club (PGA Championship),Winged Foot GC,Royal Liverpool,Austin Country Club
1,Golf Club of Houston,Memorial Park Golf Course,Ocean Course at Kiawah Island,None,Trinity Forest Golf Club,Caves Valley Golf Club,None,Congaree Golf Club,Muirfield Village Golf Club (Workday),Congressional CC (Blue),Club de Golf Chapultepec,Conway Farms GC,Glen Oaks Club,TPC Craig Ranch (Par 71),The Concession Golf Club,Innisbrook Resort (Copperhead Course),Southern Hills Country Club,None,Whistling Straits,Sherwood Country Club
2,Liberty National Golf Club,PGA National Resort (The Champion),None,None,None,Keene Trace Golf Club (Champions Course),None,None,Quail Hollow Club,Hamilton Golf &amp; Country Club,Oak Hill Country Club,Crooked Stick GC,Muirfield Village Golf Club,The Summit Club,None,Olympia Fields Country Club (North Course),None,None,None,TPC Louisiana
3,Medinah Country Club (No. 3),Pebble Beach Golf Links,None,None,None,RTJ Trail (Grand National),None,None,TPC San Antonio (Oaks Course),Harbour Town Golf Links,Pebble Beach Golf Links (U.S. Open),East Lake Golf Club,TPC Sawgrass (THE PLAYERS Stadium Course),None,None,Plainfield CC,None,None,None,TPC Summerlin
4,PGA National Resort (The Champion - Par 71),Ridgewood CC,None,None,None,Sea Island Golf Club (Seaside),None,None,Wilmington Country Club,Oakdale Golf &amp; Country Club,None,Glen Abbey GC,The Los Angeles Country Club (North Course),None,None,The Renaissance Club,None,None,None,TPC Twin Cities
5,PGA West (Palmer),Silverado Resort and Spa (North Course),None,None,None,Sedgefield Country Club,None,None,None,None,None,TPC Four Seasons Resort,Trump National Doral,None,None,The Riviera Country Club,None,None,None,None
6,Pete Dye Stadium Course,St. George's G&amp;CC,None,None,None,TPC Deere Run,None,None,None,None,None,TPC River Highlands,None,None,None,Torrey Pines Golf Course (South Course),None,None,None,None
7,Robert Trent Jones GC,TPC Boston,None,None,None,Waialae Country Club,None,None,None,None,None,TPC Scottsdale (Stadium Course),None,None,None,None,None,None,None,None
8,The Country Club of Jackson,TPC Harding Park,None,None,None,None,None,None,None,None,None,TPC Southwind,None,None,None,None,None,None,None,None
9,The Old White TPC,TPC Potomac at Avenel Farm,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
10,Vidanta Vallarta,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None